version: '3'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  cassandradb:
    image: library/cassandra:3.11.7
    container_name: cassandradb
    ports:
      - "9042:9042"
#  springboot-app-producer:
#    ports:
#      - "8081:8081"
#    build:
#      context: ./producer
#      args:
#        JAR_FILE: spring-boot-event-driven-ms-producer.jar
#      dockerfile: DockerFile
#    restart: always
#  springboot-app-consumer:
#    ports:
#      - "8082:8082"
#    build:
#      context: ./consumer
#      args:
#        JAR_FILE: spring-boot-event-driven-ms-consumer.jar
#      dockerfile: DockerFile
#    restart: always